### PR TITLE
Create CODEOWNERS

### LINKED ISSUE #1: Creation of code owner files.

### PR DESCRIPTION
**Pull request by srihub123**
## Purpose

* ...
Testing the code
## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by learnprofile — CHANGES_REQUESTED** [review]
Please modify line 1

**Comment by srihub123** [comment]
> Please modify line 1

Changes are made.

**Comment by srihub123** [comment]
,,,,

**Review by learnprofile — APPROVED** [review]

**Review by arvinddr123 — APPROVED** [review]
approving

**Pull request merged**
